name: refinery-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - refinery-secrets.yaml
      - refinery-values.yaml
      - kubeletstats-daemonset.yaml

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  HONEYCOMB_API_ENDPOINT: ${{ vars.HONEYCOMB_API_ENDPOINT }}
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  refinery-deploy:
    # don't run when creating the repo from this template
    if: github.run_number != 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Validate and set secrets
        run: |
          if [[ "${{ env.AWS_REGION }}" == "eu-west-1" ]]; then
            if [[ -z "${{ secrets.AWS_GH_EKS_ROLE_EU }}" ]] || [[ -z "${{ secrets.ACM_ARN_EU }}" ]] || [[ -z "${{ secrets.DNS_NAME_EU }}" ]]; then
              echo "Required EU secrets are not set"
              exit 1
            fi
            echo "SELECTED_EKS_ROLE=${{ secrets.AWS_GH_EKS_ROLE_EU }}" >> $GITHUB_ENV
            echo "SELECTED_ACM_ARN=${{ secrets.ACM_ARN_EU }}" >> $GITHUB_ENV
            echo "SELECTED_DNS_NAME=${{ secrets.DNS_NAME_EU }}" >> $GITHUB_ENV
          elif [[ "${{ env.AWS_REGION }}" == "us-east-1" ]]; then
            if [[ -z "${{ secrets.AWS_GH_EKS_ROLE }}" ]] || [[ -z "${{ secrets.ACM_ARN }}" ]] || [[ -z "${{ secrets.DNS_NAME }}" ]]; then
              echo "Required US secrets are not set"
              exit 1
            fi
            echo "SELECTED_EKS_ROLE=${{ secrets.AWS_GH_EKS_ROLE }}" >> $GITHUB_ENV
            echo "SELECTED_ACM_ARN=${{ secrets.ACM_ARN }}" >> $GITHUB_ENV
            echo "SELECTED_DNS_NAME=${{ secrets.DNS_NAME }}" >> $GITHUB_ENV
          else
            echo "Invalid AWS_REGION: ${{ env.AWS_REGION }}"
            exit 1
          fi

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.SELECTED_EKS_ROLE }}
          role-session-name: ci-run-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}  --kubeconfig ./kubeconfig
          echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
          echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        with:
          command: |
            kubectl create secret generic raas-secrets --from-literal=refinery-metrics-api-key=${{ secrets.REFINERY_HONEYCOMB_API_KEY }} --from-literal=refinery-query-auth-token=${{ secrets.REFINERY_QUERY_AUTH_TOKEN }} --dry-run=client -o yaml | kubectl -n ${{ vars.K8S_NAMESPACE }} apply -f -
            helm repo add honeycomb https://honeycombio.github.io/helm-charts
            helm repo update
            helm upgrade -n ${{vars.K8S_NAMESPACE}} --install refinery honeycomb/refinery -f refinery-values.yaml \
            --set ingress.annotations."alb\.ingress\.kubernetes\.io/certificate-arn"="${{ env.SELECTED_ACM_ARN }}" \
            --set ingress.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="${{ env.SELECTED_DNS_NAME }}" \
            --set ingress.hosts[0].host="${{ env.SELECTED_DNS_NAME }}" \
            --set grpcIngress.annotations."alb\.ingress\.kubernetes\.io/certificate-arn"="${{ env.SELECTED_ACM_ARN }}" \
            --set grpcIngress.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="${{ env.SELECTED_DNS_NAME }}" \
            --set grpcIngress.hosts[0].host="${{ env.SELECTED_DNS_NAME }}" \
            --set config.Network.HoneycombAPI="${{ env.HONEYCOMB_API_ENDPOINT }}:443" \
            --wait --debug
