name: refinery-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - refinery-values.yaml
      - .github/workflows/refinery-deploy.yaml

env:
  HONEYCOMB_REFINERY_TELEMETRY_API_ENDPOINT: ${{ vars.HONEYCOMB_REFINERY_TELEMETRY_API_ENDPOINT }}
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  refinery-deploy:
    # don't run when creating the repo from this template
    if: github.run_number != 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - region: us-east-1
            cluster: raas-us1
            customer_api_endpoint: https://api.honeycomb.io
            eks_role_secret: AWS_GH_EKS_ROLE_US1
            acm_arn_secret: ACM_ARN_US1
            dns_name_var: DNS_NAME_US1
            cache_endpoint_secret: CACHE_ENDPOINT_US1
          - region: eu-west-1
            cluster: raas-eu1
            customer_api_endpoint: https://api.eu1.honeycomb.io
            eks_role_secret: AWS_GH_EKS_ROLE_EU1
            acm_arn_secret: ACM_ARN_EU1
            dns_name_var: DNS_NAME_EU1
            cache_endpoint_secret: CACHE_ENDPOINT_EU1
          - region: us-east-2
            cluster: raas-us2
            customer_api_endpoint: https://api.honeycomb.io
            eks_role_secret: AWS_GH_EKS_ROLE_US2
            acm_arn_secret: ACM_ARN_US2
            dns_name_var: DNS_NAME_US2
            cache_endpoint_secret: CACHE_ENDPOINT_US2
          - region: us-west-2
            cluster: raas-us4
            customer_api_endpoint: https://api.honeycomb.io
            eks_role_secret: AWS_GH_EKS_ROLE_US4
            acm_arn_secret: ACM_ARN_US4
            dns_name_var: DNS_NAME_US4
            cache_endpoint_secret: CACHE_ENDPOINT_US4
          - region: ap-south-1
            cluster: raas-in1
            customer_api_endpoint: https://api.honeycomb.io
            eks_role_secret: AWS_GH_EKS_ROLE_IN1
            acm_arn_secret: ACM_ARN_IN1
            dns_name_var: DNS_NAME_IN1
            cache_endpoint_secret: CACHE_ENDPOINT_IN1
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[matrix.eks_role_secret] }}
          role-session-name: ci-run-${{ github.run_id }}
          aws-region: ${{ matrix.region }}

      - name: kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ matrix.cluster }} --region ${{ matrix.region }}  --kubeconfig ./kubeconfig
          echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
          echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        with:
          command: |
            kubectl create secret generic raas-secrets \
              --from-literal=refinery-metrics-api-key=${{ secrets.REFINERY_HONEYCOMB_API_KEY }} \
              --from-literal=refinery-query-auth-token=${{ secrets.REFINERY_QUERY_AUTH_TOKEN }} \
              --dry-run=client \
              -o yaml | kubectl -n ${{ vars.K8S_NAMESPACE }} apply -f -

            helm repo add honeycomb https://honeycombio.github.io/helm-charts
            helm repo update

            helm upgrade \
              -n ${{ vars.K8S_NAMESPACE }} \
              --install refinery \
              honeycomb/refinery \
              -f refinery-values.yaml \
              --set ingress.annotations."alb\.ingress\.kubernetes\.io/certificate-arn"="${{ secrets[matrix.acm_arn_secret] }}" \
              --set ingress.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="${{ vars[matrix.dns_name_var] }}" \
              --set ingress.hosts[0].host="${{ vars[matrix.dns_name_var] }}" \
              --set grpcIngress.annotations."alb\.ingress\.kubernetes\.io/certificate-arn"="${{ secrets[matrix.acm_arn_secret] }}" \
              --set grpcIngress.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="${{ vars[matrix.dns_name_var] }}" \
              --set grpcIngress.hosts[0].host="${{ vars[matrix.dns_name_var] }}" \
              --set config.Network.HoneycombAPI="${{ matrix.customer_api_endpoint }}:443" \
              --set config.HoneycombLogger.APIHost="${{ env.HONEYCOMB_REFINERY_TELEMETRY_API_ENDPOINT }}" \
              --set config.HoneycombLogger.AdditionalAttributes."aws\.region"="${{ matrix.region }}" \
              --set config.HoneycombLogger.AdditionalAttributes."k8s\.cluster\.name"="${{ matrix.cluster }}" \
              --set config.OTelMetrics.APIHost="${{ env.HONEYCOMB_REFINERY_TELEMETRY_API_ENDPOINT }}" \
              --set redis.existingHost="${{ secrets[matrix.cache_endpoint_secret] }}" \
              --set config.RedisPeerManagement.Host="${{ secrets[matrix.cache_endpoint_secret] }}" \
              --wait \
              --debug
