name: Terraform Honeycomb Triggers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**.tf"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  REFINERY_HONEYCOMB_API_KEY: ${{ secrets.REFINERY_HONEYCOMB_API_KEY }}
  KUBE_NAMESPACE: ${{ vars.K8S_NAMESPACE }}

jobs:
  terraform-download-apply-upload:
    # don't run when creating the repo from this template
    if: github.run_number != 1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Validate and set secrets
        run: |
          if [[ "${{ env.AWS_REGION }}" == "eu-west-1" ]]; then
            if [[ -z "${{ secrets.AWS_GH_EKS_ROLE_EU }}" ]] || [[ -z "${{ secrets.ACM_ARN_EU }}" ]] || [[ -z "${{ secrets.DNS_NAME_EU }}" ]]; then
              echo "Required EU secrets are not set"
              exit 1
            fi
            echo "SELECTED_EKS_ROLE=${{ secrets.AWS_GH_EKS_ROLE_EU }}" >> $GITHUB_ENV
          elif [[ "${{ env.AWS_REGION }}" == "us-east-1" ]]; then
            if [[ -z "${{ secrets.AWS_GH_EKS_ROLE }}" ]] || [[ -z "${{ secrets.ACM_ARN }}" ]] || [[ -z "${{ secrets.DNS_NAME }}" ]]; then
              echo "Required US secrets are not set"
              exit 1
            fi
            echo "SELECTED_EKS_ROLE=${{ secrets.AWS_GH_EKS_ROLE }}" >> $GITHUB_ENV
          else
            echo "Invalid AWS_REGION: ${{ env.AWS_REGION }}"
            exit 1
          fi
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.SELECTED_EKS_ROLE }}
          role-session-name: ci-run-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}
      - name: kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}  --kubeconfig ~/.kubeconfig
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform apply
        run: terraform apply -auto-approve
